//! `jotter --generate <DIR>` (hidden): the docs site's reference pages, built
//! from `ui::HELP`, `config::Config` and the clap definition, plus the man page
//! and shell completions. docs.yml and release.yml run it, so the published
//! reference can't drift from the code.

use crate::config::Config;
use anyhow::Result;
use clap_complete::Shell;
use std::fmt::Write as _;
use std::path::Path;

pub fn generate(mut cmd: clap::Command, dir: &Path) -> Result<()> {
    std::fs::create_dir_all(dir.join("man"))?;
    std::fs::create_dir_all(dir.join("completions"))?;
    std::fs::write(dir.join("keybindings.md"), keybindings())?;
    std::fs::write(dir.join("configuration.md"), configuration())?;
    std::fs::write(dir.join("cli.md"), cli(&mut cmd))?;
    clap_mangen::Man::new(cmd.clone())
        .render(&mut std::fs::File::create(dir.join("man/jotter.1"))?)?;
    let completions = dir.join("completions");
    for shell in [Shell::Bash, Shell::Zsh, Shell::Fish] {
        clap_complete::generate_to(shell, &mut cmd, "jotter", &completions)?;
    }
    clap_complete::generate_to(
        clap_complete_nushell::Nushell,
        &mut cmd,
        "jotter",
        &completions,
    )?;
    Ok(())
}

fn page(title: &str, description: &str, slug: &str, source: &str) -> String {
    format!(
        "---\ntitle: {title:?}\ndescription: {description:?}\nslug: {slug}\n---\n\n\
         <!-- generated by `jotter --generate` from {source}; edit the source, not this file -->\n\n"
    )
}

/// `"j k"` → `` `j` `k` ``: HELP keys are space-separated chords.
fn chords(keys: &str) -> String {
    keys.split(' ')
        .map(|k| format!("`{k}`"))
        .collect::<Vec<_>>()
        .join(" ")
}

fn keybindings() -> String {
    let mut s = page(
        "Keybindings",
        "Every key jOtter binds, grouped as in the in-app help.",
        "reference/keybindings",
        "HELP in src/ui.rs",
    );
    s += "Press `?` inside jOtter for the same list. Keys separated by spaces are alternatives or a pair (for example `j` `k`: next / previous). Most notebook-mode keys take a count, as in vim: `3j`, `5G`.\n";
    for (section, rows) in crate::ui::HELP {
        let _ = write!(s, "\n## {section}\n\n| Keys | Action |\n| --- | --- |\n");
        for (keys, what) in *rows {
            let _ = writeln!(s, "| {} | {what} |", chords(keys));
        }
    }
    s
}

/// `(field, type, doc)` for each `Config` field, read from the doc comments in
/// config.rs, so the struct stays the single source of truth.
fn config_fields() -> Vec<(&'static str, &'static str, String)> {
    let src = include_str!("config.rs");
    let body = src.split("pub struct Config {").nth(1).unwrap_or_default();
    let body = body.split("\n}").next().unwrap_or_default();
    let mut doc = Vec::new();
    let mut fields = Vec::new();
    for line in body.lines().map(str::trim) {
        if let Some(d) = line.strip_prefix("///") {
            doc.push(match d.trim() {
                "" => "\n\n", // paragraph break
                d => d,
            });
        } else if let Some((name, ty)) = line.strip_prefix("pub ").and_then(|l| l.split_once(':')) {
            fields.push((
                name.trim(),
                ty.trim().trim_end_matches(','),
                doc.join(" ").replace(" \n\n ", "\n\n"),
            ));
            doc.clear();
        }
    }
    fields
}

fn configuration() -> String {
    let mut s = page(
        "Configuration",
        "Every option in config.toml, with its type and default.",
        "reference/configuration",
        "the Config struct in src/config.rs",
    );
    s += "jOtter reads `$XDG_CONFIG_HOME/jotter/config.toml` (usually `~/.config/jotter/config.toml`) once at startup. The file is optional and so is every key: anything missing takes its default. A typo or an unknown key is not silently ignored: jOtter starts with all defaults and shows a warning in the status line.\n\n";
    let defaults = toml::Table::try_from(Config::default()).expect("Config serializes");
    s += "## Defaults\n\nA complete file with every key at its default value:\n\n```toml\n";
    s += &toml::to_string(&Config::default()).expect("Config serializes"); // struct order
    s += "```\n\n## Options\n";
    for (name, ty, doc) in config_fields() {
        let ty = match ty {
            "bool" => "boolean",
            "String" => "string",
            _ => "integer",
        };
        let default = defaults
            .get(name)
            .map(|v| v.to_string())
            .unwrap_or_default();
        let _ = write!(
            s,
            "\n### `{name}`\n\n**Type:** {ty} · **Default:** `{default}`\n\n{doc}\n"
        );
    }
    s
}

fn cli(cmd: &mut clap::Command) -> String {
    cmd.build();
    let mut s = page(
        "Command line",
        "jOtter's command-line arguments.",
        "reference/cli",
        "the clap Args in src/main.rs",
    );
    let _ = write!(
        s,
        "```\n{}\n```\n\n| Argument | Description |\n| --- | --- |\n",
        cmd.render_usage()
    );
    for arg in cmd.get_arguments().filter(|a| !a.is_hide_set()) {
        let value = match arg.get_value_names() {
            Some(v) if arg.get_action().takes_values() => format!(" <{}>", v.join(" ")),
            _ => String::new(),
        };
        let name = match (arg.get_short(), arg.get_long()) {
            (Some(short), Some(long)) => format!("`-{short}`, `--{long}`"),
            (None, Some(long)) => format!("`--{long}{value}`"),
            _ => format!("`{}`", value.trim()),
        };
        let help = arg.get_help().map(|h| h.to_string()).unwrap_or_default();
        let _ = writeln!(s, "| {name} | {help} |");
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A new Config field without a doc comment (or a parser miss) fails here.
    #[test]
    fn every_config_field_is_documented() {
        let defaults = toml::Table::try_from(Config::default()).unwrap();
        let fields = config_fields();
        let mut names: Vec<_> = fields.iter().map(|f| f.0).collect();
        names.sort_unstable(); // Table is a BTreeMap
        assert_eq!(
            names,
            defaults.keys().map(String::as_str).collect::<Vec<_>>()
        );
        for (name, _, doc) in fields {
            assert!(!doc.is_empty(), "config field `{name}` has no doc comment");
        }
    }
}
